services:
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: txsplitdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: