// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/shopspring/decimal"
)

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GroupBalance struct {
	GroupID  int64  `json:"group_id"`
	UserName string `json:"user_name"`
	Balance  int32  `json:"balance"`
}

type GroupMember struct {
	ID         int64     `json:"id"`
	GroupID    int64     `json:"group_id"`
	MemberName *string   `json:"member_name"`
	UserID     *int64    `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Split struct {
	ID            int64           `json:"id"`
	TransactionID int64           `json:"transaction_id"`
	TxAmount      decimal.Decimal `json:"tx_amount"`
	SplitPercent  decimal.Decimal `json:"split_percent"`
	SplitAmount   decimal.Decimal `json:"split_amount"`
	SplitUser     *int64          `json:"split_user"`
	CreatedAt     time.Time       `json:"created_at"`
	ModifiedAt    time.Time       `json:"modified_at"`
}

type Transaction struct {
	ID              int64           `json:"id"`
	GroupID         int64           `json:"group_id"`
	Name            string          `json:"name"`
	TransactionDate time.Time       `json:"transaction_date"`
	Amount          decimal.Decimal `json:"amount"`
	Category        *string         `json:"category"`
	Note            *string         `json:"note"`
	ByUser          int64           `json:"by_user"`
	CreatedAt       time.Time       `json:"created_at"`
	ModifiedAt      time.Time       `json:"modified_at"`
}

type User struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}
