// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/shopspring/decimal"
)

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GroupBalance struct {
	GroupID   int64           `json:"group_id"`
	Creditor  int64           `json:"creditor"`
	Debtor    *int64          `json:"debtor"`
	TotalOwed decimal.Decimal `json:"total_owed"`
}

type GroupBalancesNet struct {
	GroupID    int64           `json:"group_id"`
	UserID     int64           `json:"user_id"`
	NetBalance decimal.Decimal `json:"net_balance"`
}

type GroupMember struct {
	ID         int64     `json:"id"`
	GroupID    int64     `json:"group_id"`
	MemberName *string   `json:"member_name"`
	UserID     *int64    `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Split struct {
	ID            int64           `json:"id"`
	TransactionID int64           `json:"transaction_id"`
	TxAmount      decimal.Decimal `json:"tx_amount"`
	SplitPercent  decimal.Decimal `json:"split_percent"`
	SplitAmount   decimal.Decimal `json:"split_amount"`
	SplitUser     *int64          `json:"split_user"`
	CreatedAt     time.Time       `json:"created_at"`
	ModifiedAt    time.Time       `json:"modified_at"`
}

type Transaction struct {
	ID              int64           `json:"id"`
	GroupID         int64           `json:"group_id"`
	Name            string          `json:"name"`
	TransactionDate time.Time       `json:"transaction_date"`
	Amount          decimal.Decimal `json:"amount"`
	Category        *string         `json:"category"`
	Note            *string         `json:"note"`
	ByUser          int64           `json:"by_user"`
	CreatedAt       time.Time       `json:"created_at"`
	ModifiedAt      time.Time       `json:"modified_at"`
}

type User struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	CreatedAt     time.Time `json:"created_at"`
	ModifiedAt    time.Time `json:"modified_at"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
}

type UserBalancesByMember struct {
	UserID       *int64          `json:"user_id"`
	MemberUserID *int64          `json:"member_user_id"`
	NetBalance   decimal.Decimal `json:"net_balance"`
}

type UserBalancesNet struct {
	UserID     *int64          `json:"user_id"`
	NetBalance decimal.Decimal `json:"net_balance"`
}
