// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateGroup(ctx context.Context, name string) (Group, error)
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error)
	CreateSplit(ctx context.Context, arg CreateSplitParams) (Split, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteGroup(ctx context.Context, id int64) (Group, error)
	DeleteGroupMember(ctx context.Context, id int64) (GroupMember, error)
	DeleteGroupMembersByGroupID(ctx context.Context, groupID int64) ([]GroupMember, error)
	DeleteSplit(ctx context.Context, id int64) (Split, error)
	DeleteTransaction(ctx context.Context, id int64) (Transaction, error)
	DeleteTransactionSplits(ctx context.Context, transactionID int64) ([]Split, error)
	DeleteUser(ctx context.Context, id int64) (User, error)
	GetGroupByID(ctx context.Context, id int64) (Group, error)
	GetGroupByIDForUpdate(ctx context.Context, id int64) (Group, error)
	GetGroupMemberByID(ctx context.Context, id int64) (GetGroupMemberByIDRow, error)
	GetSplitByID(ctx context.Context, id int64) (Split, error)
	GetSplitByIDForUpdate(ctx context.Context, id int64) (Split, error)
	GetSplitsByTransactionID(ctx context.Context, transactionID int64) ([]Split, error)
	GetSplitsByTransactionIDForUpdate(ctx context.Context, transactionID int64) ([]Split, error)
	GetSplitsByUser(ctx context.Context, arg GetSplitsByUserParams) ([]Split, error)
	GetTransactionByID(ctx context.Context, id int64) (Transaction, error)
	GetTransactionByIDForUpdate(ctx context.Context, id int64) (Transaction, error)
	GetTransactionsByGroupInPeriod(ctx context.Context, arg GetTransactionsByGroupInPeriodParams) ([]Transaction, error)
	GetTransactionsByUser(ctx context.Context, arg GetTransactionsByUserParams) ([]Transaction, error)
	GetTransactionsByUserInPeriod(ctx context.Context, arg GetTransactionsByUserInPeriodParams) ([]Transaction, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GroupBalances(ctx context.Context, groupID int64) ([]GroupBalancesRow, error)
	GroupBalancesNet(ctx context.Context, groupID int64) ([]GroupBalancesNetRow, error)
	ListGroupMembersByGroupID(ctx context.Context, arg ListGroupMembersByGroupIDParams) ([]ListGroupMembersByGroupIDRow, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListSplits(ctx context.Context, arg ListSplitsParams) ([]Split, error)
	ListSplitsForTransaction(ctx context.Context, transactionID int64) ([]Split, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupMember(ctx context.Context, arg UpdateGroupMemberParams) (GroupMember, error)
	UpdateSplit(ctx context.Context, arg UpdateSplitParams) (Split, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Returns balances by group for a specific user
	// Only includes groups where the user is a member (filtered via WHERE gm.user_id = $1)
	// This is the correct place to filter by user membership for security and performance
	UserBalancesByGroup(ctx context.Context, userID *int64) ([]UserBalancesByGroupRow, error)
	UserBalancesByMember(ctx context.Context, userID *int64) ([]UserBalancesByMemberRow, error)
	UserBalancesSummary(ctx context.Context, userID *int64) (UserBalancesSummaryRow, error)
	getTransactionsByGroup(ctx context.Context, arg getTransactionsByGroupParams) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
