// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
/*
refresh token queries
Table structure:
CREATE TABLE "refresh_tokens" (
  "id" bigserial PRIMARY KEY,
  "token_hash" varchar NOT NULL,
  "user_id" bigint NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "revoked_at" timestamptz,
  "device_info" varchar,
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);
*/

INSERT INTO "refresh_tokens" (token_hash, user_id, expires_at, device_info)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, user_id, expires_at, created_at, revoked_at, device_info
`

type CreateRefreshTokenParams struct {
	TokenHash  string    `json:"token_hash"`
	UserID     int64     `json:"user_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	DeviceInfo *string   `json:"device_info"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM "refresh_tokens"
WHERE expires_at < now() OR (revoked_at IS NOT NULL AND revoked_at < now() - INTERVAL '30 days')
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, user_id, expires_at, created_at, revoked_at, device_info FROM "refresh_tokens"
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.DeviceInfo,
	)
	return i, err
}

const getUserRefreshTokens = `-- name: GetUserRefreshTokens :many
SELECT id, token_hash, user_id, expires_at, created_at, revoked_at, device_info FROM "refresh_tokens"
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) GetUserRefreshTokens(ctx context.Context, userID int64) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getUserRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.DeviceInfo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE "refresh_tokens"
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE "refresh_tokens"
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
