// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
/*
user queries
Table structure:
CREATE TABLE "users" (
  "id" bigserial PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "email_verified" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "modified_at" timestamptz NOT NULL DEFAULT (now())
);
*/

INSERT INTO "users" (name) 
VALUES ($1) 
RETURNING id, name, created_at, modified_at, email, password_hash, email_verified
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const createUserWithAuth = `-- name: CreateUserWithAuth :one
INSERT INTO "users" (name, email, password_hash) 
VALUES ($1, $2, $3) 
RETURNING id, name, created_at, modified_at, email, password_hash, email_verified
`

type CreateUserWithAuthParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUserWithAuth(ctx context.Context, arg CreateUserWithAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithAuth, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM "users"
WHERE id = $1
RETURNING id, name, created_at, modified_at, email, password_hash, email_verified
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
  id, name, created_at, modified_at, email, password_hash, email_verified 
FROM "users"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
  id, name, created_at, modified_at, email, password_hash, email_verified 
FROM "users"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
  id, name, created_at, modified_at, email, password_hash, email_verified 
FROM "users"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET name = $1
WHERE id = $2
RETURNING id, name, created_at, modified_at, email, password_hash, email_verified
`

type UpdateUserParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
	)
	return i, err
}
